[workspace]
members = [
	"client/cli",
	"client/consensus/aura",
	"client/consensus/common",
	"client/consensus/relay-chain",
	"client/network",
	"client/pov-recovery",
	"client/service",
	"pallets/aura-ext",
	"pallets/dmp-queue",
	"pallets/parachain-system",
	"pallets/xcm",
	"pallets/xcmp-queue",
	"primitives/core",
	"primitives/parachain-inherent",
	"primitives/utility",
	"polkadot-parachains/",
	"polkadot-parachains/pallets/parachain-info",
	"polkadot-parachains/pallets/ping",
	"polkadot-parachains/rococo-runtime",
	"polkadot-parachains/shell-runtime",
	"test/runtime",
	"test/runtime-upgrade",
	"test/client",
	"test/service",
	"test/relay-sproof-builder",
	"test/relay-validation-worker-provider",
]

[profile.release]
panic = "unwind"

[patch.'https://github.com/paritytech/substrate']
sp-core = { git="https://github.com/cheme/substrate", branch="state-update4" }
sc-client-api = { git="https://github.com/cheme/substrate", branch="state-update4" }
pallet-treasury = { git="https://github.com/cheme/substrate", branch="state-update4" }
pallet-randomness-collective-flip = { git="https://github.com/cheme/substrate", branch="state-update4" }
pallet-babe = { git="https://github.com/cheme/substrate", branch="state-update4" }
sp-trie = { git="https://github.com/cheme/substrate", branch="state-update4" }
sp-keyring = { git="https://github.com/cheme/substrate", branch="state-update4" }
pallet-timestamp = { git="https://github.com/cheme/substrate", branch="state-update4" }
frame-system = { git="https://github.com/cheme/substrate", branch="state-update4" }
frame-try-runtime = { git="https://github.com/cheme/substrate", branch="state-update4" }
frame-system-benchmarking = { git="https://github.com/cheme/substrate", branch="state-update4" }
pallet-staking = { git="https://github.com/cheme/substrate", branch="state-update4" }
frame-support = { git="https://github.com/cheme/substrate", branch="state-update4" }
pallet-session = { git="https://github.com/cheme/substrate", branch="state-update4" }
pallet-balances = { git="https://github.com/cheme/substrate", branch="state-update4" }
pallet-authorship = { git="https://github.com/cheme/substrate", branch="state-update4" }
sp-staking = { git="https://github.com/cheme/substrate", branch="state-update4" }
sp-runtime = { git="https://github.com/cheme/substrate", branch="state-update4" }
sp-io = { git="https://github.com/cheme/substrate", branch="state-update4" }
sp-std = { git="https://github.com/cheme/substrate", branch="state-update4" }
sp-inherents = { git="https://github.com/cheme/substrate", branch="state-update4" }
sp-api = { git="https://github.com/cheme/substrate", branch="state-update4" }
pallet-sudo = { git="https://github.com/cheme/substrate", branch="state-update4" }
frame-system-rpc-runtime-api = { git="https://github.com/cheme/substrate", branch="state-update4" }
pallet-staking-reward-curve = { git="https://github.com/cheme/substrate", branch="state-update4" }
pallet-offences = { git="https://github.com/cheme/substrate", branch="state-update4" }
pallet-nicks = { git="https://github.com/cheme/substrate", branch="state-update4" }
pallet-membership = { git="https://github.com/cheme/substrate", branch="state-update4" }
pallet-indices = { git="https://github.com/cheme/substrate", branch="state-update4" }
pallet-im-online = { git="https://github.com/cheme/substrate", branch="state-update4" }
pallet-identity = { git="https://github.com/cheme/substrate", branch="state-update4" }
pallet-grandpa = { git="https://github.com/cheme/substrate", branch="state-update4" }
frame-executive = { git="https://github.com/cheme/substrate", branch="state-update4" }
pallet-elections-phragmen = { git="https://github.com/cheme/substrate", branch="state-update4" }
pallet-election-provider-multi-phase = { git="https://github.com/cheme/substrate", branch="state-update4" }
frame-election-provider-support = { git="https://github.com/cheme/substrate", branch="state-update4" }
frame-metadata = { git="https://github.com/cheme/substrate", branch="state-update4" }
frame-support-test = { git="https://github.com/cheme/substrate", branch="state-update4" }
remote-externalities = { git="https://github.com/cheme/substrate", branch="state-update4" }
sc-informant = { git="https://github.com/cheme/substrate", branch="state-update4" }
sc-finality-grandpa-warp-sync = { git="https://github.com/cheme/substrate", branch="state-update4" }
sp-database = { git="https://github.com/cheme/substrate", branch="state-update4" }
substrate-browser-utils = { git="https://github.com/cheme/substrate", branch="state-update4" }
try-runtime-cli = { git="https://github.com/cheme/substrate", branch="state-update4" }
pallet-democracy = { git="https://github.com/cheme/substrate", branch="state-update4" }
pallet-collective = { git="https://github.com/cheme/substrate", branch="state-update4" }
pallet-transaction-payment-rpc = { git="https://github.com/cheme/substrate", branch="state-update4" }
pallet-transaction-payment-rpc-runtime-api = { git="https://github.com/cheme/substrate", branch="state-update4" }
pallet-transaction-payment = { git="https://github.com/cheme/substrate", branch="state-update4" }
pallet-authority-discovery = { git="https://github.com/cheme/substrate", branch="state-update4" }
sp-transaction-pool = { git="https://github.com/cheme/substrate", branch="state-update4" }
sp-version = { git="https://github.com/cheme/substrate", branch="state-update4" }
sp-session = { git="https://github.com/cheme/substrate", branch="state-update4" }
sp-offchain = { git="https://github.com/cheme/substrate", branch="state-update4" }
sp-consensus-babe = { git="https://github.com/cheme/substrate", branch="state-update4" }
pallet-recovery = { git="https://github.com/cheme/substrate", branch="state-update4" }
pallet-society = { git="https://github.com/cheme/substrate", branch="state-update4" }
fork-tree = { git="https://github.com/cheme/substrate", branch="state-update4" }
pallet-utility = { git="https://github.com/cheme/substrate", branch="state-update4" }
sc-network = { git="https://github.com/cheme/substrate", branch="state-update4" }
sc-cli = { git="https://github.com/cheme/substrate", branch="state-update4" }
sc-client-db = { git="https://github.com/cheme/substrate", branch="state-update4" }
sc-executor = { git="https://github.com/cheme/substrate", branch="state-update4" }
sc-service = { git="https://github.com/cheme/substrate", branch="state-update4" }
sc-keystore = { git="https://github.com/cheme/substrate", branch="state-update4" }
sp-authority-discovery = { git="https://github.com/cheme/substrate", branch="state-update4" }
sp-block-builder = { git="https://github.com/cheme/substrate", branch="state-update4" }
sp-blockchain = { git="https://github.com/cheme/substrate", branch="state-update4" }
sc-network-gossip = { git="https://github.com/cheme/substrate", branch="state-update4" }
sp-state-machine = { git="https://github.com/cheme/substrate", branch="state-update4" }
sp-externalities = { git="https://github.com/cheme/substrate", branch="state-update4" }
sp-runtime-interface = { git="https://github.com/cheme/substrate", branch="state-update4" }
sp-application-crypto = { git="https://github.com/cheme/substrate", branch="state-update4" }
sp-serializer = { git="https://github.com/cheme/substrate", branch="state-update4" }
sc-rpc = { git="https://github.com/cheme/substrate", branch="state-update4" }
substrate-frame-rpc-system = { git="https://github.com/cheme/substrate", branch="state-update4" }
sc-authority-discovery = { git="https://github.com/cheme/substrate", branch="state-update4" }
sc-chain-spec = { git="https://github.com/cheme/substrate", branch="state-update4" }
sc-finality-grandpa = { git="https://github.com/cheme/substrate", branch="state-update4" }
sc-telemetry = { git="https://github.com/cheme/substrate", branch="state-update4" }
sc-transaction-pool = { git="https://github.com/cheme/substrate", branch="state-update4" }
sp-timestamp = { git="https://github.com/cheme/substrate", branch="state-update4" }
sc-block-builder = { git="https://github.com/cheme/substrate", branch="state-update4" }
sp-finality-grandpa = { git="https://github.com/cheme/substrate", branch="state-update4" }
sp-tracing = { git="https://github.com/cheme/substrate", branch="state-update4" }
substrate-prometheus-endpoint = { git="https://github.com/cheme/substrate", branch="state-update4" }
sp-keystore = { git="https://github.com/cheme/substrate", branch="state-update4" }
frame-benchmarking = { git="https://github.com/cheme/substrate", branch="state-update4" }
frame-benchmarking-cli = { git="https://github.com/cheme/substrate", branch="state-update4" }
pallet-bounties = { git="https://github.com/cheme/substrate", branch="state-update4" }
pallet-multisig = { git="https://github.com/cheme/substrate", branch="state-update4" }
pallet-scheduler = { git="https://github.com/cheme/substrate", branch="state-update4" }
pallet-tips = { git="https://github.com/cheme/substrate", branch="state-update4" }
pallet-proxy = { git="https://github.com/cheme/substrate", branch="state-update4" }
pallet-vesting = { git="https://github.com/cheme/substrate", branch="state-update4" }
sc-basic-authorship = { git="https://github.com/cheme/substrate", branch="state-update4" }
sp-consensus = { git="https://github.com/cheme/substrate", branch="state-update4" }
sp-consensus-slots = { git="https://github.com/cheme/substrate", branch="state-update4" }
sc-consensus = { git="https://github.com/cheme/substrate", branch="state-update4" }
sc-consensus-babe = { git="https://github.com/cheme/substrate", branch="state-update4" }
sc-consensus-babe-rpc = { git="https://github.com/cheme/substrate", branch="state-update4" }
sc-consensus-epochs = { git="https://github.com/cheme/substrate", branch="state-update4" }
sc-consensus-slots = { git="https://github.com/cheme/substrate", branch="state-update4" }
sp-consensus-vrf = { git="https://github.com/cheme/substrate", branch="state-update4" }
sp-consensus-aura = { git="https://github.com/cheme/substrate", branch="state-update4" }
sp-wasm-interface = { git="https://github.com/cheme/substrate", branch="state-update4" }
sc-finality-grandpa-rpc = { git="https://github.com/cheme/substrate", branch="state-update4" }
sc-light = { git="https://github.com/cheme/substrate", branch="state-update4" }
sc-sync-state-rpc = { git="https://github.com/cheme/substrate", branch="state-update4" }
sp-arithmetic = { git="https://github.com/cheme/substrate", branch="state-update4" }
sp-storage = { git="https://github.com/cheme/substrate", branch="state-update4" }
sc-tracing = { git="https://github.com/cheme/substrate", branch="state-update4" }
sp-test-primitives = { git="https://github.com/cheme/substrate", branch="state-update4" }
substrate-build-script-utils = { git="https://github.com/cheme/substrate", branch="state-update4" }
substrate-test-client = { git="https://github.com/cheme/substrate", branch="state-update4" }
substrate-test-runtime = { git="https://github.com/cheme/substrate", branch="state-update4" }
substrate-test-runtime-client = { git="https://github.com/cheme/substrate", branch="state-update4" }
substrate-test-utils = { git="https://github.com/cheme/substrate", branch="state-update4" }
substrate-wasm-builder = { git="https://github.com/cheme/substrate", branch="state-update4" }
sp-npos-elections = { git="https://github.com/cheme/substrate", branch="state-update4" }
sp-npos-elections-compact = { git="https://github.com/cheme/substrate", branch="state-update4" }
pallet-offences-benchmarking = { git="https://github.com/cheme/substrate", branch="state-update4" }
pallet-session-benchmarking = { git="https://github.com/cheme/substrate", branch="state-update4" }
pallet-gilt = { git="https://github.com/cheme/substrate", branch="state-update4" }
pallet-mmr = { git="https://github.com/cheme/substrate", branch="state-update4" }
pallet-mmr-primitives = { git="https://github.com/cheme/substrate", branch="state-update4" }
pallet-mmr-rpc = { git="https://github.com/cheme/substrate", branch="state-update4" }
sp-rpc = { git="https://github.com/cheme/substrate", branch="state-update4" }
pallet-staking-reward-fn = { git="https://github.com/cheme/substrate", branch="state-update4" }
sp-maybe-compressed-blob = { git="https://github.com/cheme/substrate", branch="state-update4" }
sc-executor-common = { git="https://github.com/cheme/substrate", branch="state-update4" }
sc-executor-wasmtime = { git="https://github.com/cheme/substrate", branch="state-update4" }
sc-consensus-uncles = { git="https://github.com/cheme/substrate", branch="state-update4" }
sp-authorship = { git="https://github.com/cheme/substrate", branch="state-update4" }
sp-utils = { git="https://github.com/cheme/substrate", branch="state-update4" }
pallet-assets = { git="https://github.com/cheme/substrate", branch="state-update4" }
pallet-aura = { git="https://github.com/cheme/substrate", branch="state-update4" }
sc-consensus-aura = { git="https://github.com/cheme/substrate", branch="state-update4" }

[patch.'https://github.com/paritytech/polkadot']
kusama-runtime = { git="https://github.com/cheme/polkadot-1", branch="state-update4" }
westend-runtime = { git="https://github.com/cheme/polkadot-1", branch="state-update4" }
rococo-runtime = { git="https://github.com/cheme/polkadot-1", branch="state-update4" }
polkadot-cli = { git="https://github.com/cheme/polkadot-1", branch="state-update4" }
polkadot-rpc = { git="https://github.com/cheme/polkadot-1", branch="state-update4" }
polkadot-parachain = { git="https://github.com/cheme/polkadot-1", branch="state-update4" }
polkadot-collator-protocol = { git="https://github.com/cheme/polkadot-1", branch="state-update4" }
polkadot-primitives = { git="https://github.com/cheme/polkadot-1", branch="state-update4" }
polkadot-core-primitives = { git="https://github.com/cheme/polkadot-1", branch="state-update4" }
polkadot-node-primitives = { git="https://github.com/cheme/polkadot-1", branch="state-update4" }
polkadot-node-subsystem = { git="https://github.com/cheme/polkadot-1", branch="state-update4" }
polkadot-node-jaeger = { git="https://github.com/cheme/polkadot-1", branch="state-update4" }
polkadot-node-collation-generation = { git="https://github.com/cheme/polkadot-1", branch="state-update4" }
polkadot-statement-table = { git="https://github.com/cheme/polkadot-1", branch="state-update4" }
polkadot-availability-distribution = { git="https://github.com/cheme/polkadot-1", branch="state-update4" }
polkadot-availability-bitfield-distribution = { git="https://github.com/cheme/polkadot-1", branch="state-update4" }
polkadot-overseer = { git="https://github.com/cheme/polkadot-1", branch="state-update4" }
polkadot-service = { git="https://github.com/cheme/polkadot-1", branch="state-update4" }
polkadot-runtime = { git="https://github.com/cheme/polkadot-1", branch="state-update4" }
polkadot-runtime-common = { git="https://github.com/cheme/polkadot-1", branch="state-update4" }
polkadot-runtime-parachains = { git="https://github.com/cheme/polkadot-1", branch="state-update4" }
polkadot-erasure-coding = { git="https://github.com/cheme/polkadot-1", branch="state-update4" }
polkadot-network-bridge = { git="https://github.com/cheme/polkadot-1", branch="state-update4" }
polkadot-test-runtime = { git="https://github.com/cheme/polkadot-1", branch="state-update4" }
polkadot-test-client = { git="https://github.com/cheme/polkadot-1", branch="state-update4" }
polkadot-test-service = { git="https://github.com/cheme/polkadot-1", branch="state-update4" }
polkadot-node-subsystem-test-helpers = { git="https://github.com/cheme/polkadot-1", branch="state-update4" }
polkadot-node-subsystem-util = { git="https://github.com/cheme/polkadot-1", branch="state-update4" }
xcm = { git="https://github.com/cheme/polkadot-1", branch="state-update4" }
xcm-builder = { git="https://github.com/cheme/polkadot-1", branch="state-update4" }
xcm-executor = { git="https://github.com/cheme/polkadot-1", branch="state-update4" }
pallet-xcm = { git="https://github.com/cheme/polkadot-1", branch="state-update4" }
polkadot-node-core-pvf = { git="https://github.com/cheme/polkadot-1", branch="state-update4" }

[patch.crates-io]
hash-db = { git = "https://github.com/cheme/trie.git", branch = "hashed-value-simple4-new" }
memory-db = { git = "https://github.com/cheme/trie.git", branch = "hashed-value-simple4-new" }
trie-db = { git = "https://github.com/cheme/trie.git", branch = "hashed-value-simple4-new" }
trie-root = { git = "https://github.com/cheme/trie.git", branch = "hashed-value-simple4-new" }
trie-bench = { git = "https://github.com/cheme/trie.git", branch = "hashed-value-simple4-new" }
