[package]
name = "cumulus-client-network"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Cumulus-specific networking protocol"
edition = "2018"

[dependencies]
# Substrate deps
sp-blockchain = { git = "https://github.com/paritytech/substrate", branch = "apopiak-xcm-origin" }
sp-consensus = { git = "https://github.com/paritytech/substrate", branch = "apopiak-xcm-origin" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "apopiak-xcm-origin" }
sp-api = { git = "https://github.com/paritytech/substrate", branch = "apopiak-xcm-origin" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "apopiak-xcm-origin" }
sc-client-api = { git = "https://github.com/paritytech/substrate", branch = "apopiak-xcm-origin" }

# Polkadot deps
polkadot-primitives = { git = "https://github.com/paritytech/polkadot", branch = "apopiak-xcm-origin" }
polkadot-statement-table = { git = "https://github.com/paritytech/polkadot", branch = "apopiak-xcm-origin" }
polkadot-node-primitives = { git = "https://github.com/paritytech/polkadot", branch = "apopiak-xcm-origin" }
polkadot-service = { git = "https://github.com/paritytech/polkadot", branch = "apopiak-xcm-origin" }
polkadot-parachain = { git = "https://github.com/paritytech/polkadot", branch = "apopiak-xcm-origin" }

# other deps
codec = { package = "parity-scale-codec", version = "2.0.0", features = [ "derive" ] }
futures = { version = "0.3.1", features = ["compat"] }
futures-timer = "3.0.2"
tracing = "0.1.22"
parking_lot = "0.10.2"
derive_more = "0.99.2"

[dev-dependencies]
tokio = { version = "0.2.21", features = ["macros"] }

# Cumulus deps
cumulus-test-service = { path = "../../test/service" }
cumulus-primitives-core = { path = "../../primitives/core" }

# Polkadot deps
polkadot-test-client = { git = "https://github.com/paritytech/polkadot", branch = "apopiak-xcm-origin" }

# substrate deps
sc-client-api = { git = "https://github.com/paritytech/substrate", branch = "apopiak-xcm-origin" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "apopiak-xcm-origin" }
sp-keyring = { git = "https://github.com/paritytech/substrate", branch = "apopiak-xcm-origin" }
sp-keystore = { git = "https://github.com/paritytech/substrate", branch = "apopiak-xcm-origin" }
sp-consensus = { git = "https://github.com/paritytech/substrate", branch = "apopiak-xcm-origin" }
sc-cli = { git = "https://github.com/paritytech/substrate", branch = "apopiak-xcm-origin" }
substrate-test-utils = { git = "https://github.com/paritytech/substrate", branch = "apopiak-xcm-origin" }
sc-service = { git = "https://github.com/paritytech/substrate", branch = "apopiak-xcm-origin" }
