[package]
name = "rococo-parachain-primitives"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
# Substrate dependencies
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "apopiak-xcm-origin" }
sp-core = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "apopiak-xcm-origin" }

[features]
default = [ "std" ]
std = [
	"sp-runtime/std",
	"sp-core/std"
]
